package com.diplomacy.orders.utils;

public enum verificationResult {
    OK,
    WRONG_PHASE,
    WRONG_ORDER_TYPE,
    SELECTED_PROVINCE_NOT_OCCUPIED,
    UNIT_NOT_OWNED_BY_PLAYER,
    DESTINATION_NOT_SET,
    ADDITIONAL_UNIT_NOT_SET,
    DESTINATION_NOT_REACHABLE,
    CANNOT_SUPPORT_HERE,
    MUST_BE_ARMY,
    MUST_BE_FLEET,
    FLEET_MUST_BE_IN_WATER,
    CANNOT_SUPPORT_SELF,
    PROVINCE_ALREADY_OCCUPIED,
    NOT_A_SUPPLY_CENTER,
    NOT_HOME_PROVINCE,
    UNABLE_TO_SPAWN
}
